### ISSUE TITLE
Crashes for me

### ISSUE THREAD

**Issue by peterfealey** [dreamcat4/lgremote#2]
running ruby lgremote pair throws the following error for me:

lgremote:838:in `pair_interactive': undefined method`name' for nil:NilClass (NoMethodError)
    from ./lgremote:866:in `pair'
    from ./lgremote:1024:in`main_loop'
    from ./lgremote:1034:in `<main>'

**Comment by dreamcat4** [comment]
Presumably the bug is just that the program didn't exit gracefully.

There aught to be some explanatory terminal output just before it fails as to why that was. The script should have said on the Stdout "No LG Smart TVs were found on your network." etc.
